In [2]:
import numpy as np

In [23]:
mat = np.matrix(np.random.randn(4,4))
mat_sym = mat + mat.T
mat_skew = mat - mat.T

print "mat = \n%s"%mat
print "mat_skew = \n%s"%mat_skew
print "mat_sym = \n%s"%mat_sym

mat = 
[[-1.3291372  -0.71924533 -0.146565    1.74092075]
 [ 1.17606763 -0.14154208 -0.22795465  0.69216378]
 [-1.3386868  -1.16181714 -0.26263738 -0.851776  ]
 [ 0.65159339 -0.62910012 -2.11672479 -1.51262042]]
mat_skew = 
[[ 0.         -1.89531297  1.1921218   1.08932735]
 [ 1.89531297  0.          0.93386249  1.32126391]
 [-1.1921218  -0.93386249  0.          1.2649488 ]
 [-1.08932735 -1.32126391 -1.2649488   0.        ]]
mat_sym = 
[[-2.65827441  0.4568223  -1.4852518   2.39251414]
 [ 0.4568223  -0.28308416 -1.3897718   0.06306366]
 [-1.4852518  -1.3897718  -0.52527475 -2.96850079]
 [ 2.39251414  0.06306366 -2.96850079 -3.02524083]]


## Eigenvalues of skew symmetric matrices are complex

In [24]:
print np.linalg.eigvals(mat_skew)

[ 5.89805982e-17+3.081953j    5.89805982e-17-3.081953j
 -1.11022302e-16+0.95890476j -1.11022302e-16-0.95890476j]


## Eigenvalues of symmetric matrices are real

In [26]:
print np.linalg.eigvals(mat_sym)

[ 3.15390873 -5.73353305 -3.34781639 -0.56443343]


## $I - S$, where $S$ is skew symmetric, is necessarily non-singular

In [29]:
print np.linalg.eigvals(np.identity(4) - mat_skew)
print np.linalg.inv(np.identity(4) - mat_skew)

[1.+3.081953j   1.-3.081953j   1.+0.95890476j 1.-0.95890476j]
[[ 0.25893229 -0.40622732  0.09671366 -0.13233364]
 [ 0.15289253  0.25843363 -0.08422669  0.40146659]
 [-0.40913402  0.14259516  0.37339646  0.21505236]
 [ 0.03346018 -0.07932006 -0.46639455  0.34168112]]
